### ISSUE TITLE
1 ply level is too tough

### ISSUE THREAD

**Issue by inferrna** [jcarolus/android-chess#153] opened 2023-02-23 12:58 UTC
In version 9.3.10 at this level it feels engine is playing way better than in 8.9.4. It looks more like 2 or 3 ply, which is too hard for my kid.

**Comment by jcarolus** [comment] 2023-02-24 20:09
You are right, it will now look further than configured plies in positions with captures or checks.
My sun is also complaining.
Will probably build in a setting to turn on/off this behaviour.

**Comment by jcarolus** [comment] 2023-03-01 13:48
Implemented a toggle button which enables/disables Quiescence search, because this is the root cause of difficulty. This will be in release 9.3.11
This will probably be good enough to use in combination with the nr of plies.

**Closed by jcarolus** 2023-03-01 13:48 UTC
